cappa/src/main/java/org/caprice/cappa/model/db/User.java
package org.caprice.cappa.model.db;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.caprice.cappa.model.db.enums.T_UserRole;
import java.io.Serializable;
import javax.persistence.*;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import org.caprice.cappa.model.beans.BadgeCount;
import org.caprice.cappa.model.db.views.UserStats;
import org.caprice.cappa.utils.AppUtils;
import org.caprice.cappa.utils.converters.Converters;


/**
 * The persistent class for the e_user database table.
 * 
 */
@Entity
@Table(name="e_user")
@NamedQuery(name="User.findAll", query="SELECT u FROM User u")
public class User implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;

	private Integer age;

	@Column(name="create_time")
	private Timestamp createTime;

	private String details;

	@Column(name="education_level")
	private String educationLevel;

	private String email;

        @JsonIgnore
	@Column(name="password_hash")
	private String passwordHash;

	private String profession;

	private String username;
        
        @OneToOne
        @JoinColumn(name = "id", insertable = false, updatable = false)
        private UserStats UserStats;
        
	// Field Generated by user stats
        @JsonInclude
        @Transient
	private List<BadgeCount> Rewards;
        
	// Field Generated by user stats
        @JsonInclude
        @Transient
	private int score;

	//uni-directional many-to-many association to T_UserRole
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(
		name="r_user_has_user_role"
		, joinColumns={
			@JoinColumn(name="user_id")
			}
		, inverseJoinColumns={
			@JoinColumn(name="user_role_id")
			}
		)
	private Set<T_UserRole> UserRoles;

	public User() {
	}

        public User(String email, String username, String password, Set<T_UserRole> UserRoles) {
            this.createTime = new Timestamp(System.currentTimeMillis());
            this.email = email;
            this.passwordHash = AppUtils.getMD5HashAsBase64(password);
            this.username = username;
            this.UserRoles = UserRoles;
        }
        
        public User(String email, String username, String password, Set<T_UserRole> UserRoles, String details) {
            this.createTime = new Timestamp(System.currentTimeMillis());
            this.email = email;
            this.passwordHash = AppUtils.getMD5HashAsBase64(password);
            this.username = username;
            this.UserRoles = UserRoles;
            this.details = details;
        }
        
        
        public User(String username, String password) {
            this.username = username;
            this.passwordHash = AppUtils.getMD5HashAsBase64(password);
            this.email = password;
        }

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public String getEducationLevel() {
		return this.educationLevel;
	}

	public void setEducationLevel(String educationLevel) {
		this.educationLevel = educationLevel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
        
	public List<BadgeCount> getRewards() {
                if( this.Rewards == null)
                    this.Rewards = Converters.getRewards(this.UserStats);
		return this.Rewards;
	}
        
        public int getScore() {
                if( this.score == 0){
                    if( this.Rewards == null ){
                        getRewards();
                    }
                    this.score = this.Rewards.stream()
                                .mapToInt( rc -> rc.getBadge().getScoreValue() * rc.getCount() )
                                .sum();
                }
		return this.score;
	}
        
        public UserStats getUserStats() {
            return UserStats;
        }

        public void setUserStats(UserStats stats) {
            this.UserStats = stats;
        }


	public Set<T_UserRole> getUserRoles() {
		return this.UserRoles;
	}

	public void setUserRoles(Set<T_UserRole> UserRoles) {
		this.UserRoles = UserRoles;
	}
        
        public void addUserRoles(T_UserRole role) {
		this.UserRoles.add(role);
	}
        
        public void removeUserRoles(T_UserRole role) {
		this.UserRoles.remove(role);
	}

        
    @Override
    public String toString() {
        return "User{" + "id=" + id + 
                "\n age=" + age + 
                "\n createTime=" + createTime + 
                "\n details=" + details + 
                "\n educationLevel=" + educationLevel + 
                "\n email=" + email + 
                "\n password=" + passwordHash + 
                "\n profession=" + profession + 
                "\n username=" + username + 
                "\n UserStats=" + UserStats + 
                "\n UserRoles=" + UserRoles + '}';
    }

        
        
}

cappa/src/main/webapp/WEB-INF/fragments/userDetails.jsp
<%-- 
    Document   : userDetails
    Created on : Feb 8, 2018, 5:30:31 PM
    Author     : Giorgos Hompis <ghompis@csd.uoc.gr>
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>


<%-- USER DETAILS --%>
<div class="container-fluid">
    <div class="row no-gutters">
        <div class="col-3 no-gutters px-2 card bg-light">
            <div class="text-center text-secondary p-2">
                <i class="fa fa-user" style="font-size: 8rem" aria-hidden="true"></i>
            </div>
            <div class="card-body text-center p-2">
                <h5 class="card-title font-weight-bold">${user.username}</h5>
                <p class="card-text"><span class="text-secondary">Total Score : </span>${user.score}</p>
            </div>
        </div>

        <div class="col-9 no-gutters px-2">
            <ul class="list-group">
                <li class="list-group-item py-2">
                    <span class="text-secondary">User Roles : </span> &nbsp;
                    <c:forEach var="role" items="${user.userRoles}">
                         <span class="badge badge-secondary">${role.name}</span>
                    </c:forEach>
                </li>
                <li class="list-group-item py-2">
                    <span class="text-secondary">Email : </span> <a href="mailto:${user.email}">${user.email}</a>
                </li>
                <li class="list-group-item py-2">
                    <span class="text-secondary">Age : </span> 
                    <span class="text-dark">${user.age}</span>
                </li>
                <li class="list-group-item py-2">
                    <span class="text-secondary">Profession : </span> ${user.profession}
                </li>
                <li class="list-group-item py-2">
                    <span class="text-secondary">Education Level : </span> ${user.educationLevel}
                </li>
                <li class="list-group-item py-2">
                    <span class="text-secondary pb-1">Details</span><br>&nbsp;
                    ${user.details}
                </li>
            </ul>
        </div>
    </div>
</div>


<%-- USER REWARDS --%>
<h3 class="mt-3 px-3">Rewards</h3>
<hr class="seperator">
<div class="bg-light p-3 mt-2">

    <div>
        <h6 class="text-secondary pb-2">Goal Badges</h6>
<!--                        <div class="clearfix">
            <p class="float-right">Total Valid Annotations: ${user.userStats.annotationValidatedCount}</p>
        </div>-->
        <c:forEach var="r" items="${user.rewards.stream().filter( bc -> bc.badge.category eq 'Goal').toList()}" varStatus="status" >
            <div class="d-inline" style="opacity: ${1/3.0 + 2*r.count/3.0}; width: ${status.index < 2? 33:33}%">
                <span class="badge" style="background-color: ${r.badge.uiColor}">${r.badge.name}</span>
            </div>
        </c:forEach>
    </div>
    <hr class="seperator">

    <div>
        <h6 class="text-secondary pb-2">Simple Badges</h6>
        <c:forEach var="r" items="${user.rewards.stream().filter( bc -> bc.badge.category eq 'Simple').toList()}" varStatus="status" >
            <div class="d-inline-block ${status.index < 2? "mb-3":""}" style="width: ${status.index < 2? 33:33}%">
                <span class="badge" style="background-color: ${r.badge.uiColor}">${r.badge.name}</span> x${r.count} 
            </div>
            ${status.index == 1? "<br>":""}
        </c:forEach>
    </div>
    <hr class="seperator">

    <div>
        <h6 class="text-secondary pb-2">Special Badges</h6>
        <c:forEach var="r" items="${user.rewards.stream().filter( bc -> bc.badge.category eq 'Special').toList()}">
            <div class="d-inline-block" style="width: 33%">
                <div><span class="badge" style="background-color: ${r.badge.uiColor}">${r.badge.name}</span> x${r.count}</div>
            </div>
        </c:forEach>
    </div>
</div>