cappa/src/main/java/org/caprice/cappa/model/db/Annotation.java
package org.caprice.cappa.model.db;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import org.caprice.cappa.model.db.enums.T_Tag;
import java.io.Serializable;
import javax.persistence.*;
import java.util.List;


/**
 * The persistent class for the e_annotation database table.
 * 
 */
@Entity
@Table(name="e_annotation")
@NamedQuery(name="Annotation.findAll", query="SELECT a FROM Annotation a")
@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="id")
public class Annotation implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;

	private String text;
        
	//uni-directional many-to-one association to ControversialEntity
	@ManyToOne
	@JoinColumn(name="controversial_entity_id")
	private ControversialEntity ControversialEntity;
        
	@ManyToOne
	@JoinColumn(name="legal_document_id")
	private LegalDocument LegalDocument;
        
	//bi-directional many-to-one association to TextPart
	@OneToMany(mappedBy="Annotation", cascade = {CascadeType.ALL} )
	private List<TextPart> TextParts;

	//uni-directional many-to-many association to T_Tag
	@ManyToMany
	@JoinTable(
		name="r_annotation_has_t_tag"
		, joinColumns={
			@JoinColumn(name="annotation_id")
			}
		, inverseJoinColumns={
			@JoinColumn(name="t_tag_id")
			}
		)
	private List<T_Tag> Tags;

	public Annotation() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public ControversialEntity getControversialEntity() {
		return this.ControversialEntity;
	}

	public void setControversialEntity(ControversialEntity ControversialEntity) {
		this.ControversialEntity = ControversialEntity;
	}
        
        public LegalDocument getLegalDocument() {
            return LegalDocument;
        }

        public void setLegalDocument(LegalDocument LegalDocument) {
            this.LegalDocument = LegalDocument;
        }
        
	public List<TextPart> getTextParts() {
		return this.TextParts;
	}

	public void setTextParts(List<TextPart> TextParts) {
		this.TextParts = TextParts;
	}

	public TextPart addTextPart(TextPart TextPart) {
		getTextParts().add(TextPart);
		TextPart.setAnnotation(this);

		return TextPart;
	}

	public TextPart removeTextPart(TextPart TextPart) {
		getTextParts().remove(TextPart);
		TextPart.setAnnotation(null);

		return TextPart;
	}

	public List<T_Tag> getTags() {
		return this.Tags;
	}

	public void setTags(List<T_Tag> Tags) {
		this.Tags = Tags;
	}

        @Override
        public String toString() {
            return "Annotation{" + "id=" + id + '}';
        }



}

cappa/src/main/java/org/caprice/cappa/model/db/Metadata.java
package org.caprice.cappa.model.db;

import java.io.Serializable;
import javax.persistence.*;
import java.sql.Timestamp;


/**
 * The persistent class for the e_metadata database table.
 * 
 */
@Entity
@Table(name="e_metadata")
@NamedQuery(name="Metadata.findAll", query="SELECT m FROM Metadata m")
public class Metadata implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;

	@Column(name="created_at")
	private Timestamp createdAt;

	//uni-directional many-to-one association to User
	@ManyToOne
	@JoinColumn(name="created_by_id")
	private User CreatedBy;

	public Metadata() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public User getCreatedBy() {
		return this.CreatedBy;
	}

	public void setCreatedBy(User CreatedBy) {
		this.CreatedBy = CreatedBy;
	}

}

cappa/src/main/java/org/caprice/cappa/model/db/Vote.java
package org.caprice.cappa.model.db;

import java.io.Serializable;
import javax.persistence.*;


/**
 * The persistent class for the e_user database table.
 * 
 */
@Entity
@Table(name="e_vote")
@NamedQuery(name="Vote.findAll", query="SELECT v FROM Vote v")
public class Vote implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;

        @Column(name = "vote_value")
        private int voteValue;
        
	//uni-directional many-to-one association to ControversialEntity
	@ManyToOne
	@JoinColumn(name="controversial_entity_id")
	private ControversialEntity ControversialEntity;
        
	//uni-directional many-to-one association to Metadata
	@ManyToOne
	@JoinColumn(name="metadata_id")
	private Metadata Metadata;
        
        
	public Vote() {
	}

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

        public int getVoteValue() {
            return voteValue;
        }

        public void setVoteValue(int voteValue) {
            this.voteValue = voteValue;
        }

        public ControversialEntity getControversialEntity() {
            return ControversialEntity;
        }

        public void setControversialEntity(ControversialEntity ControversialEntity) {
            this.ControversialEntity = ControversialEntity;
        }

        public Metadata getMetadata() {
            return Metadata;
        }

        public void setMetadata(Metadata Metadata) {
            this.Metadata = Metadata;
        }

        @Override
        public String toString() {
            return "Vote{" + "id=" + id + ", voteValue=" + voteValue + ", ControversialEntity=" + ControversialEntity + ", Metadata=" + Metadata + '}';
        }
        
}

cappa/src/main/java/org/caprice/cappa/flow/controller/rest/data/AnnotationController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.caprice.cappa.flow.controller.rest.data;

/**
 *
 * @author Giorgos Hompis <ghompis@csd.uoc.gr>
 */

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.caprice.cappa.flow.repository.AnnotationRepository;
import org.caprice.cappa.flow.repository.LegalDocumentRepository;
import org.caprice.cappa.model.formBeans.NewAnnotationForm;
import org.caprice.cappa.model.db.User;
import org.caprice.cappa.flow.repository.UserRepository;
import org.caprice.cappa.flow.service.AnnotationService;
import org.caprice.cappa.model.beans.ExceptionMessage;
import org.caprice.cappa.model.db.Annotation;
import org.caprice.cappa.model.restBeans.DataServerResponse;
import org.caprice.cappa.model.restBeans.ServerResponse;
import org.caprice.cappa.utils.SessionUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ViewResolver;

@RestController("AnnotationData")
@RequestMapping(value = "/product/{productId}/document/{documentId}/annotation")
public class AnnotationController {
    
    @Autowired
    ViewResolver viewResolver;
    
    @Autowired
    UserRepository userRepository;
    @Autowired
    LegalDocumentRepository documentRepository;
    @Autowired
    AnnotationRepository annotationRepository;
    
    @Autowired
    AnnotationService annotationService;
    
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public DataServerResponse getAnnotationData(HttpServletRequest request,
            @PathVariable("id") Integer annotationId, 
            ModelMap model) {
        Annotation a = annotationRepository.findOne(annotationId);
        return DataServerResponse.get(ServerResponse.Status.SUCCESS, "Success", a);
    }
    
    
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public DataServerResponse deleteAnnotation(HttpServletRequest request,
            @PathVariable("productId") Integer productId, 
            @PathVariable("documentId") Integer documentId, 
            @PathVariable("id") Integer annotationId, 
            ModelMap model) {
        Annotation a = annotationRepository.findOne(annotationId);
        if( a != null ) {
            annotationRepository.delete(a);
            return DataServerResponse.get(ServerResponse.Status.SUCCESS, "Success", a);
        }
        else{
            return DataServerResponse.get(ServerResponse.Status.DANGER, "Could not find the given annotation", null);
        }
    }
    
    
    @RequestMapping(value = "/new", method = RequestMethod.POST)
    public DataServerResponse createAnnotation(HttpServletRequest request,
            @PathVariable("productId") Integer productId, 
            @PathVariable("documentId") Integer documentId, 
            ModelMap model, @Valid @RequestBody NewAnnotationForm annotationForm, BindingResult bindingResult) {
        User user = SessionUtils.getLoggedInUser(userRepository, request);
        try {
            Annotation a = annotationService.createNewAnnotation(user, documentId, annotationForm);
            return DataServerResponse.get(ServerResponse.Status.SUCCESS, "Annotation successfully created!", a);
        } catch (ExceptionMessage ex) {
            return ex.getDataResponse();
        }
    }
    
}

cappa/src/main/java/org/caprice/cappa/flow/controller/rest/view/AnnotationController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.caprice.cappa.flow.controller.rest.view;

/**
 *
 * @author Giorgos Hompis <ghompis@csd.uoc.gr>
 */

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.caprice.cappa.config.Definitions;
import org.caprice.cappa.flow.repository.AnnotationRepository;
import org.caprice.cappa.flow.repository.LegalDocumentRepository;
import org.caprice.cappa.model.formBeans.NewAnnotationForm;
import org.caprice.cappa.model.db.enums.T_Tag;
import org.caprice.cappa.model.db.User;
import org.caprice.cappa.flow.repository.UserRepository;
import org.caprice.cappa.flow.repository.VoteRepository;
import org.caprice.cappa.flow.service.AnnotationService;
import org.caprice.cappa.model.beans.ExceptionMessage;
import org.caprice.cappa.model.db.Annotation;
import org.caprice.cappa.model.db.ControversialEntity;
import org.caprice.cappa.model.db.Vote;
import org.caprice.cappa.model.restBeans.DataServerResponse;
import org.caprice.cappa.model.restBeans.ServerResponse;
import org.caprice.cappa.model.restBeans.ViewServerResponse;
import org.caprice.cappa.utils.RenderUtils;
import org.caprice.cappa.utils.SessionUtils;
import org.caprice.cappa.utils.converters.TextHighlightUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ViewResolver;

@RestController("AnnotationView")
@RequestMapping(value = "/product/{productId}/document/{documentId}/annotation")
public class AnnotationController {
    
    @Autowired
    ViewResolver viewResolver;
    
    @Autowired
    UserRepository userRepository;
    @Autowired
    LegalDocumentRepository documentRepository;
    @Autowired
    AnnotationRepository annotationRepository;
    @Autowired
    VoteRepository voteRepository;
    
    @Autowired
    AnnotationService annotationService;
    
    
    
    
    @RequestMapping(value = "/new", method = RequestMethod.POST)
    public ViewServerResponse createAnnotation(HttpServletRequest request,
            @PathVariable("productId") Integer productId, 
            @PathVariable("documentId") Integer documentId, 
            ModelMap model, @Valid @RequestBody NewAnnotationForm annotationForm, BindingResult bindingResult) {
        User user = SessionUtils.getLoggedInUser(userRepository, request);
        
        try {
            Annotation a = annotationService.createNewAnnotation(user, documentId, annotationForm);
            model.put("annotation", a);
            String html = RenderUtils.renderView("annotation/annotation", viewResolver, request, model);
            return ViewServerResponse.get(ServerResponse.Status.SUCCESS, "Annotation successfully created!", html);
        } catch (ExceptionMessage ex) {
            return ex.getViewResponse();
        }
    }
    
    
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public ViewServerResponse getAnnotationDetailsView(HttpServletRequest request,
            @PathVariable("id") Integer annotationId, 
            ModelMap model) {
        User user = SessionUtils.getLoggedInUser(userRepository, request);
        Map<ControversialEntity, Vote> votesByEntity = Collections.EMPTY_MAP;
        if( user != null ){
            votesByEntity = voteRepository.getByUser(user).stream()
                    .collect( Collectors.toMap( vote -> vote.getControversialEntity(), vote -> vote));
        }
        Annotation a = annotationRepository.findOne(annotationId);
        model.put("annotation", a);
        model.put("votesByEntity", votesByEntity);
        String html = RenderUtils.renderView("annotation/annotation", viewResolver, request, model);
        return ViewServerResponse.get(ServerResponse.Status.SUCCESS, "success", html);
    }
    
    
}

cappa/src/main/webapp/WEB-INF/fragments/annotation/annotation.jsp
<%-- any content can be specified here e.g.: --%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/functions" prefix = "fn" %>
<%@ page pageEncoding="UTF-8" %>


<li class="py-2" style="list-style: none; ${(fn:toLowerCase(annotation.controversialEntity.state.name) == "invalid")? "opacity:.5":""}" data-annotation="${annotation.id}">
    <div class="container-fluid no-gutters">
        <div class="row no-gutters">
            
            <%-- Score + Votes UI --%>
            <div class="col-2 no-gutters rating text-center px-md-1">

                <div class="row" style="position: absolute">
                    <!--<div class="px-1">-->
                        <!--
                        <c:if test='${fn:toLowerCase(annotation.controversialEntity.state.name) == "unclarified"}' >
                            <i class="fa fa-question text-secondary px-1" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="This annotation has not been clarified yet"></i>
                        </c:if>
                        -->
                        <c:if test='${fn:toLowerCase(annotation.controversialEntity.state.name) == "valid"}' >
                            <i class="fa fa-check fa-lg text-success px-1" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="This annotation is valid"></i>
                        </c:if>
                        <c:if test='${fn:toLowerCase(annotation.controversialEntity.state.name) == "invalid"}' >
                            <i class="fa fa-times fa-lg text-danger px-1" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="This annotation is invalid"></i>
                        </c:if>
                        <i class="fa fa-eye-slash fa-lg px-1" aria-hidden="true" data-icon="annotation-not-visible" style="display: none;"
                           data-toggle="tooltip" data-placement="top" title="Highlights Not Visible due to highlight conflicts"></i>
                    <!--</div>-->
                </div>

                <div class="row">

                    <div class="col-7 p-0 m-auto ">
                        <div class="rounded w-50 float-right font-weight-bold ${fn:toLowerCase(annotation.controversialEntity.state.name) == "invalid"? "badge-danger" : 
                                            fn:toLowerCase(annotation.controversialEntity.state.name) == "valid"? "badge-success" : "badge-light" }" 
                                style="font-size:1.5rem; line-height: 2;" data-toggle="tooltip" data-placement="top" 
                                title="Up: ${annotation.controversialEntity.votes.votesUp} 
                                <br> Down: ${annotation.controversialEntity.votes.votesDown}
                                <br> Min Confidence: <fmt:formatNumber type="number" maxFractionDigits="2" value="${annotation.controversialEntity.minConfidenceLimit}" />
                                <br> Max Confidence: <fmt:formatNumber type="number" maxFractionDigits="2" value="${annotation.controversialEntity.maxConfidenceLimit}" />" >
                                ${annotation.controversialEntity.votes.votesUp - annotation.controversialEntity.votes.votesDown}
                        </div>
                    </div>

                    <div class="col-5 p-1 px-3 badge rounded ">
                        <div class="p-1">
                            <button type="button" onclick="submitVote(${annotation.controversialEntity.id}, 1, ${annotation.id})" class="btn btn-outline-success ${votesByEntity[annotation.controversialEntity].voteValue>0? 'selected':''}" 
                                    style="padding:.2rem .6rem;" data-toggle="tooltip" data-placement="top" title="This annotation seems useful and provides valid information">
                                <i class="fa fa-sort-up" aria-hidden="true"></i>
                            </button>
                        </div>
                        <div class="p-1">
                            <button type="button" onclick="submitVote(${annotation.controversialEntity.id}, -1, ${annotation.id})" class="btn btn-outline-danger ${votesByEntity[annotation.controversialEntity].voteValue<0? 'selected':''}"
                                    style="padding:.2rem .6rem;" data-toggle="tooltip" data-placement="top" title="This annotation seems useless or provides invalid information">
                                <i class="fa fa-sort-down" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>

                </div>
                
                
            </div>
            
            
            
            <div class="col-10 context px-3 no-gutters">
                
                <div class="row mb-2 no-gutters">
                    <!-- Tags -->
                    <div class="col-10">
                        <div class='clearfix'>
                            <div class="py-1">
                                <c:forEach var="tag" items="${annotation.tags}">
                                    <span class="badge" data-toggle="tooltip" data-placement="top" title="${tag.description}"
                                          style="cursor: help; background-color: ${annotation.tags[0].privacyConcern.uiColor}">
                                        ${tag.tagAttribute.name}: <b>${tag.name}</b>
                                    </span>
                                </c:forEach>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 d-inline-block text-right">
                        <!-- Focus Button -->
                        <div class='d-inline-block text-right px-2 text-secondary' style='cursor: pointer' data-toggle="tooltip" data-placement="top" title="Click to focus"
                             onclick="documentViewer.focusOnAnnotationClicked(${annotation.id})">
                            <i class="fa fa-external-link fa-lg" aria-hidden="true"></i>
                        </div>
                        <!-- Info Button -->
                        <div class='d-inline-block text-right px-2 text-secondary' style='cursor: pointer' data-toggle="tooltip" data-placement="top"  data-icon="highlightText"
                             title="Highlighted Text">
                            <i class="fa fa-info-circle fa-lg " aria-hidden="true"></i>
                        </div>
                        <!-- Trash Button -->
                        <div class='d-inline-block text-right px-2 text-secondary' style='cursor: pointer' data-toggle="tooltip" data-placement="top" title="Delete Annotation" data-icon='deleteAnnotation'
                             onclick="setDeleteEntityModal('Are you sure you want to delete this annotation?', ${annotation.controversialEntity.id}, ${annotation.id})" data-toggle="modal" data-target="#delete-entity-modal">
                            <i class="fa fa-trash fa-lg"></i>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <!-- Comment -->
                    <div class="col-9 ">
                        <p>
                            ${annotation.text}
                        </p>
                    </div>
                    <!-- User Details -->
                    <div class="col-3">
                        
                        <div class="d-inline-block clearfix w-100">
                            
                            <div class="float-right bg-light border border-secondary rounded p-md-2">
                                <div class="align-middle">
                                    <h1 class="d-inline py-3 pr-2 pl-1 text-secondary"><i class="fa fa-user" aria-hidden="true"></i></h1>
                                    <div class="d-inline-block float-right">
                                        <div>
                                            by 
                                            <a href="#" onclick="loadUserDetails(${annotation.controversialEntity.metadata.createdBy.id})" data-toggle="modal" data-target="#user-modal" data-button="show-user">
                                                ${annotation.controversialEntity.metadata.createdBy.username}
                                            </a> 
                                        </div>
                                            <span class="text-secondary text-right" data-toggle="tooltip" data-placement="top" title="<fmt:formatDate value="${annotation.controversialEntity.metadata.createdAt}" pattern="EEEE',' dd MMMM yyyy 'at' hh:mm a"/>" >
                                            on <fmt:formatDate value="${annotation.controversialEntity.metadata.createdAt}" pattern="dd/MM/yyyy"/>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                
            </div>

        </div>
    </div>
    <hr/>

</li>