cappa/src/main/java/org/caprice/cappa/model/db/DigitalProduct.java
package org.caprice.cappa.model.db;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import org.caprice.cappa.model.db.enums.T_BusinessCategory;
import java.io.Serializable;
import javax.persistence.*;
import java.util.List;
import java.util.SortedSet;
import org.caprice.cappa.model.db.enums.T_DigitalProductType;


/**
 * The persistent class for the e_digital_product database table.
 * 
 */
@Entity
@Table(name="e_digital_product")
@NamedQuery(name="DigitalProduct.findAll", query="SELECT d FROM DigitalProduct d")
@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="id")
public class DigitalProduct implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;

	private String name;
        
	private String url;
        
	@Column(name="logo_image_path")
	private String logoImagePath;

	@Column(name="logo_image_base64")
        private String logoImageData;
        
	//uni-directional many-to-one association to Metadata
	@ManyToOne
	@JoinColumn(name="controversial_entity_id")
	private ControversialEntity ControversialEntity;

	//bi-directional many-to-one association to LegalDocument
	@OneToMany(mappedBy="DigitalProduct", fetch = FetchType.EAGER)
        @OrderBy("id ASC")
	private SortedSet<LegalDocument> LegalDocuments;

	//uni-directional many-to-many association to T_BusinessCategory
	@ManyToMany
	@JoinTable(
		name="r_digital_product_has_t_business_category"
		, joinColumns={
			@JoinColumn(name="digital_product_id")
			}
		, inverseJoinColumns={
			@JoinColumn(name="t_business_category_id")
			}
		)
	private List<T_BusinessCategory> BusinessCategories;
        
	//uni-directional many-to-one association to T_DigitalProductType
	@ManyToOne
	@JoinColumn(name="digital_product_type_id")
        private T_DigitalProductType ProductType;

        
	public DigitalProduct() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }

        public String getLogoImagePath() {
            return logoImagePath;
        }
        
        public void setLogoImagePath(String logoImagePath) {
            this.logoImagePath = logoImagePath;
        }

        public String getLogoImageData() {
            return logoImageData;
        }

        public void setLogoImageData(String logoImageData) {
            this.logoImageData = logoImageData;
        }

        public ControversialEntity getControversialEntity() {
            return ControversialEntity;
        }

        public void setControversialEntity(ControversialEntity ControversialEntity) {
            this.ControversialEntity = ControversialEntity;
        }

	public SortedSet<LegalDocument> getLegalDocuments() {
		return this.LegalDocuments;
	}

	public void setLegalDocuments(SortedSet<LegalDocument> LegalDocuments) {
		this.LegalDocuments = LegalDocuments;
	}

	public LegalDocument addLegalDocument(LegalDocument LegalDocument) {
		getLegalDocuments().add(LegalDocument);
		LegalDocument.setDigitalProduct(this);

		return LegalDocument;
	}

	public LegalDocument removeLegalDocument(LegalDocument LegalDocument) {
		getLegalDocuments().remove(LegalDocument);
		LegalDocument.setDigitalProduct(null);

		return LegalDocument;
	}

	public List<T_BusinessCategory> getBusinessCategories() {
		return this.BusinessCategories;
	}

	public void setBusinessCategories(List<T_BusinessCategory> BusinessCategories) {
		this.BusinessCategories = BusinessCategories;
	}

        public T_DigitalProductType getProductType() {
            return ProductType;
        }

        public void setProductType(T_DigitalProductType ProductType) {
            this.ProductType = ProductType;
        }
        

}

cappa/src/main/webapp/WEB-INF/jspf/digitalProduct/tabs.jspf
<%-- any content can be specified here e.g.: --%>
<%@page import="org.caprice.model.db.LegalDocument"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page pageEncoding="UTF-8" %>
<%@taglib prefix="tabs" tagdir="/WEB-INF/tags/digitalProduct/" %>


<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="documents-tab" data-toggle="tab" href="#documents" role="tab" aria-controls="documents" aria-selected="true">Documents</a>
    </li>
<!--    <li class="nav-item">
        <a class="nav-link" id="permissions-tab" data-toggle="tab" href="#permissions" role="tab" aria-controls="permissions" aria-selected="false">Permissions</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="externalResources-tab" data-toggle="tab" href="#externalResources" role="tab" aria-controls="externalResources" aria-selected="false">External Resources</a>
    </li>-->
</ul>
    
<div class="tab-content" id="myTabContent">
    
    
    <%-- Documents --%>
    <div class="tab-pane fade show active" id="documents" role="tabpanel" aria-labelledby="home-tab">
        <div class="px-md-3 py-md-5">
            
            <%-- Add Button --%>
            <div class="float-right mx-3">
                <%@include file="/WEB-INF/jspf/digitalProduct/modal/addDocumentForm.jspf" %>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#document-modal" data-button="new-document">
                    <i class="fa fa-plus fa-fw" aria-hidden="true"></i>
                    Add New Document
                </button>
            </div>
            <div class="clearfix"></div>
            
            <%-- Documents Lists --%>
<!--            <ul>
                <c:forEach var="document" items="${product.legalDocuments}">
                    <li> <tabs:document document="${document}" /> </li>
                </c:forEach>
            </ul> -->
            
            <div class="row no-gutters">
                <c:forEach var="documentEntry" items="${documents}">
                    
                    <div class="col-12 text-center py-2 row"> 
                        <div class="btn-group w-100 py-2">
                            <div class="text-left d-inline-block w-100  rounded-left">
                                <tabs:document document="${documentEntry.key}" />
                            </div>
                            <button type="button" class="col-2 d-inline-block btn btn-light rounded-right border-top-0 border-bottom-0 border-right-0 border-secondary dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <a class="text-primary">
                                    <u>All Versions</u>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </a>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right w-100 p-3 mt-1 border border-secondary">
                                <c:forEach var="document" items="${documentEntry.value}">
                                    <div class='m-3 mr-5'>
                                        <tabs:document document="${document}" />
                                    </div>
                                    <!--<hr class="bg-secondary">-->
                                </c:forEach>
                            </div>
                        </div>
                    </div>
                </c:forEach>
            </div>


            
        </div>
    </div>
    
    
    <%-- Permissions --%>
    <div class="tab-pane fade" id="permissions" role="tabpanel" aria-labelledby="profile-tab">
        
    </div>
    
    
    <%-- External Resources --%>
    <div class="tab-pane fade" id="externalResources" role="tabpanel" aria-labelledby="contact-tab">
        
    </div>
    
</div>
    